# Generated by Django 4.2.4 on 2023-08-11 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_rename_user_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin', models.CharField(max_length=10)),
                ('price', models.BigIntegerField(default=10)),
                ('amount', models.BigIntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Account', to='account.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
