# Generated by Django 4.2.4 on 2023-08-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('order', '0004_order_external_checkout_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin', to='coin.coin'),
        ),
    ]
