# Generated by Django 4.2.4 on 2023-08-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_user_userprofile"),
        ("order", "0005_alter_order_coin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=18, verbose_name="Crypto purchase price"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=18, verbose_name="Crypto sales price"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=18, verbose_name="order total price"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="account",
                to="account.userprofile",
            ),
        ),
    ]
