# Generated by Django 4.2.4 on 2023-08-12 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "abbreviation_name",
                    models.CharField(max_length=20, verbose_name="abbreviation name"),
                ),
                ("purchase_price", models.BigIntegerField()),
                ("sale_price", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
