# Generated by Django 4.2.4 on 2023-08-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='abbreviation_name',
        ),
    ]
