# Generated by Django 4.2.4 on 2023-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coin", "0003_coin_abbreviation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="abbreviation_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="coin",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="coin",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="coin",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
